version: '3'

services: 
    aesm:
        image: sgx-aesm
        devices:
            - /dev/isgx
        volumes:
            - /tmp/aesmd:/var/run/aesmd
        stdin_open: true
        tty: true
        environment:
            - http_proxy
            - https_proxy
        
    tester:
        image: sgx-tester
        depends_on:
            - aesm
        devices:
            - /dev/isgx
        volumes:
            - /tmp/aesmd:/var/run/aesmd
        stdin_open: true
        tty: true